import { createClient } from '@/lib/supabase/server';
import { type BlogPostContent, buildFAQSchema, calculateReadingTime } from './blog-generator';
import { generateBlogImage } from './image-generator';
import { matchCounselingProgram } from './cta-matcher';

export interface PublishInput {
  content: BlogPostContent;
  categoryId: string;
  authorId?: string;
  targetAudience: 'client' | 'professional';
  status?: 'draft' | 'published';
  skipImage?: boolean;
}

export interface PublishResult {
  success: boolean;
  postId?: string;
  slug?: string;
  error?: string;
  steps: {
    image: boolean;
    ctaMatch: boolean;
    dbSave: boolean;
  };
}

/**
 * Blog publishing pipeline (local execution):
 * 1. Generate thumbnail image (Gemini API) — optional
 * 2. Match CTA counseling program
 * 3. Save to Supabase
 *
 * Content is provided externally (generated by Claude Code).
 */
export async function publishBlogPost(input: PublishInput): Promise<PublishResult> {
  const { content } = input;
  const steps = { image: false, ctaMatch: false, dbSave: false };

  // Step 1: Generate image (non-blocking)
  let thumbnailUrl: string | null = null;
  if (!input.skipImage) {
    console.log('[publish] Step 1: Generating image...');
    try {
      thumbnailUrl = await generateBlogImage(
        content.slug,
        content.visual_keywords || []
      );
      steps.image = thumbnailUrl !== null;
      console.log(steps.image ? `[publish] Image: ${thumbnailUrl}` : '[publish] Image skipped');
    } catch (error) {
      console.warn('[publish] Image error (non-fatal):', error);
    }
  } else {
    console.log('[publish] Step 1: Image skipped (skipImage flag)');
  }

  // Step 2: Match CTA counseling program
  console.log('[publish] Step 2: Matching CTA...');
  let counselingProgramId: string | null = null;
  try {
    const allKeywords = [...content.keywords];
    const matchResult = await matchCounselingProgram(allKeywords);
    if (matchResult) {
      counselingProgramId = matchResult.id;
      steps.ctaMatch = true;
      console.log(`[publish] CTA matched: ${matchResult.title}`);
    } else {
      console.log('[publish] No CTA match (will use category default)');
    }
  } catch (error) {
    console.warn('[publish] CTA match error (non-fatal):', error);
  }

  // Step 3: Save to Supabase
  console.log('[publish] Step 3: Saving to DB...');
  try {
    const supabase = await createClient();
    const ctaType = input.targetAudience === 'professional' ? 'education' : 'consultation';
    const schemaMarkup = buildFAQSchema(content.faq || []);
    const readingTime = calculateReadingTime(content.content);

    const { data, error } = await supabase
      .from('posts')
      .insert({
        title: content.title,
        slug: content.slug,
        content: content.content,
        excerpt: content.excerpt,
        summary: content.summary,
        keywords: content.keywords,
        category_id: input.categoryId,
        author_id: input.authorId || null,
        status: input.status || 'draft',
        meta_title: content.meta_title,
        meta_description: content.meta_description,
        schema_markup: schemaMarkup as any,
        references: content.references as any,
        thumbnail_url: thumbnailUrl,
        counseling_program_id: counselingProgramId,
        reading_time: readingTime,
        cta_type: ctaType,
        published_at: input.status === 'published' ? new Date().toISOString() : null,
      } as any)
      .select('id, slug')
      .single() as { data: { id: string; slug: string } | null; error: any };

    if (error) {
      return { success: false, error: `DB error: ${error.message}`, steps };
    }

    steps.dbSave = true;
    console.log(`[publish] Saved: ${data?.id}`);
    return { success: true, postId: data?.id, slug: data?.slug, steps };
  } catch (error) {
    return { success: false, error: `DB error: ${error}`, steps };
  }
}
